apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-dummy
  namespace: rtf 
  labels:
    business-group: business-group-id
    environment: environment-id
spec:
  ingressClassName: rtf-nginx 
  #tls: 
  #- hosts:
      #- rtf.example.com
    #secretName: example-tls
  rules:
  - host: rtf.example.com
    http:
      paths: 
      - pathType: Prefix
        path: /
        backend: 
          service:
            name: service-name
            port:
              name: service-port
