apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-dummy
  namespace: rtf 
  labels:
    business-group: business-group-id
    environment: environment-id
spec:
  ingressClassName: rtf-nginx 
  tls: 
  - hosts:
      - app-name.example.com
    secretName: example-tls
  rules:
    - host: app-name.example.com 
      http:
        paths: 
        - path: /
          pathType:
          backend: 
            serviceName: service-name
            servicePort: 80
