apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-dummy-example
  namespace: gke-dummy 
  labels:
    business-group: business-group-id
    environment: environment-id
spec:
  ingressClassName: rtf-nginx 
  
  rules:
    - host: rtf.example.com
      http:
        paths: 
        - path: /
          pathType:
          backend: 
            serviceName: service-name
            servicePort: 80
