apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
      #rewrite ^/app-name(/|$)(.*) /$2 break;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  name: rtf-ingress-template
  namespace: rtf
  labels:
    business-group: business-group-id
    environment: environment-id
spec:
  ingressClassName: rtf-nginx
  #rules:
  tls:
  - hosts:
      - rtf.example.com
    secretName: nginx-ingress-tls
  rules:
  - host: rtf.example.com
    http:
      paths: 
      - pathType: ImplementationSpecific
        path: /app-name/(.*)
        backend: 
          service:
            name: service-name
            port:
              number: 80
